### ISSUE TITLE
Parameters k and d

### ISSUE THREAD

**Issue by caillonantoine** [dhgrs/chainer-VQ-VAE#11]
Hi,

in `params.py` you've choosen k=128 and d=512, when in the original paper it is stated that k should be 512 and d should be 1... Any reason to take those values in particular?

**Comment by dhgrs** [comment]
Sorry for late reply. `k=128` is from [author's demo](https://avdnoord.github.io/homepage/vqvae/). And `d=512` from second paragraph in 4.3 Audio in the [paper](https://arxiv.org/pdf/1711.00937v2.pdf). Could you tell me why did you think so?

**Comment by caillonantoine** [comment]
Hi, thank you for your response. Actually you are right, I was misunderstanding the way they describe the quantized latent space. Your code has made it very clear, thanks again!
