### ISSUE TITLE
Vq loss and commitment loss

### ISSUE THREAD

**Issue by partha2409** [dhgrs/chainer-VQ-VAE#12]
Hi, does loss2 and loss3 numerically differ just by the scalar factor of 'beta'? For eg: if beta is 0.25, and loss2 = 0.4, then is loss3 is 0.25 * 0.4 = 0.1 ? 

If yes, i do not clearly understand why we have to use both the terms, if reduction of loss2 directly means reduction of loss3? can you please explain.

**Comment by dhgrs** [comment]
Hi, thanks for interest.

The answer for the first question is yes. So loss2 and loss3 numerically differ just by the scalar factor of 'beta'. But decreasing loss2 differs from decreasing loss3. The details are written in original paper. Loss2 is second term and loss3 is third term in equation(3).
