### ISSUE TITLE
Implementation jitter in chainer

### ISSUE THREAD

**Issue by shiva1393** [dhgrs/chainer-VQ-VAE#13]
Hai, I runned this code ,now i tried giving mfcc features as input ....i tried to keep jitter() function but iam not able to do... In pytorch i know
can you help to write this script in chainer...
In torch
class Jitter(nn.Module):
    def __init__(self, probability=0.12):
        super(Jitter, self).__init__()
        self._probability = probability
    def forward(self, quantized):
        original_quantized = quantized.detach().clone()
        length = original_quantized.size(2)
        for i in range(length):
            replace = [True, False][np.random.choice([1, 0], p=[self._probability, 1 - self._probability])]
            if replace:
                if i == 0:
                    neighbor_index = i + 1
                elif i == length - 1:
                    neighbor_index = i - 1
                else:
                    neighbor_index = i + np.random.choice([-1, 1], p=[0.5, 0.5])
                quantized[:, :, i] = original_quantized[:, :, neighbor_index]

in above code iam not able to assign 
original_quantized = quantized.detach().clone() in chainer..
Iam getting following error in chainer 
TypeError: 'Variable' object does not support item assignment

**Comment by dhgrs** [comment]
Sorry for late reply. Could you share your code with indents?

**Comment by shiva1393** [comment]
1.Jitter introduction: 

without giving input directly to wavenet, we use jitter  at time step t must strive to also be useful at time steps t − 1 or t + 1.To maintain  consistency across tokens jitter helps from "Unsupervised speech representation learning using WaveNet autoencoders" paper. 
I tried paper network but not able to do jitter in chainer.


2.To implement jitter in torch following are basics  from following discussion:https://discuss.pytorch.org/t/clone-and-detach-in-v0-4-0/16861
tensor.detach() creates a tensor that shares storage with tensor that does not require grad. tensor.clone()creates a copy of tensor that imitates the original tensor's requires_grad field.
You should use detach() when attempting to remove a tensor from a computation graph, and clone as a way to copy the tensor while still keeping the copy as a part of the computation graph it came from

3.self._probability = 0.12
Now we are giving quantized inputs to jitter
original_quantized = quantized.detach().clone()
now we replace either t-1 ot t+1 or t with 
replace = [True, False][np.random.choice([1, 0], p=[self._probability, 1 - self._probability])]
if it is true
neighbor_index = i + np.random.choice([-1, 1], p=[0.5, 0.5]) we take either left or right with 0.5 probability.
quantized[:, :, i] = original_quantized[:, :, neighbor_index]
then replace 
here iam attaching link:
which i followed:
https://github.com/swasun/VQ-VAE-Speech/blob/master/src/modules/jitter.py

Thank you for your reply

**Comment by dhgrs** [comment]
It is very hard to understand Python code without any indents. Could you share your code **with indents**? GitHub supports markdown style comment.

FYI: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by shiva1393** [comment]
Sorry ....
jitter code link i gave in above discussion to see indentation: 
link:   https://github.com/swasun/VQ-VAE-Speech/blob/master/src/modules/jitter.py

**Comment by dhgrs** [comment]
Thank you. `chainer.Variable` does not support item assignment because assignment destroys computation graph. So you can two ways to resolve it.
1. Replace assignment with calculation. For example, multiply by 0 and add new value.
1. Use cupy array or numpy array. These don't support computation graph but it's maybe no problem in this case. Like below.
```
quantized = quantized.array
```

**Comment by dhgrs** [comment]
I'm going to close but please feel free to reopen.
