### ISSUE TITLE
out of memory to allocate

### ISSUE THREAD

**Issue by jiqizaisikao** [dhgrs/chainer-VQ-VAE#2]
Hi,I used the cpu version but is seems not to work,and i tried to run gpu version but end with err:cupy.cuda.memory.OutofMemoryError:out of memory to allocate 65536000 bytes(total 7991438336)
My gpu is nvidia GTX1070

**Comment by dhgrs** [comment]
Hi, how do you set parameters in `opt.py`? It uses nearly 5.5GB(GPU) with parameters of newest commit( 7f8c94b ). GTX1070 has 8GB memories so may be able to run this code. Please check `opt.py` or other programs are running on same GPU.

**Comment by jiqizaisikao** [comment]
I download your source code  yesterday on my ubuntu
k=512
d=512
the n_channel1=256
the n_channel2=512
the n_channel3=256
your opt.py  are  much different from each other,maybe i should change it to be smaller

**Comment by dhgrs** [comment]
Yes, I'm searching the best parameters so `opt.py` are much different from each other. And the newest version that you try uses 5.5GB. Other parameters `batchsize`, `length`, `n_loop`, `n_layer` and `n_filter` change memory usage of GPU. If you changed these parameters, please try default parameters of newest commit. Althogh you can't run with these parameters, please tell me the version of chainer. I'm using chainer v3.2.0.
