### ISSUE TITLE
BatchNorm and ResidualBlocks in Encoder

### ISSUE THREAD

**Issue by pfriesch** [dhgrs/chainer-VQ-VAE#5]
Have you experimented with adding BatchNorm, Dropout or Residual Blocks to the Encoder? 

Even though, they did not mention it in the audio part of the paper, they added Residual Blocks to the encoder for the other experiments. Have you experimented with adding them?

Also they show some straight blocks between the ConvBlocks on the [demo page ](https://avdnoord.github.io/homepage/vqvae/).

**Comment by dhgrs** [comment]
I have not. 

In the audio part of the paper; "the encoder has 6 strided convolutions with stride 2 and window-size 4" So the encoder may not have any residual blocks in author's implementation. But it's worth trying batchnorm, dropout and residual blocks I think! Can you try it?

FYI: In Chapter Reconstructions in demo page, there is no speaker condition. But it needs. I think this demo page doesn't express exactly implementation.

**Comment by pfriesch** [comment]
The voice conversion is the last entry. They call it "Voice Style-Transfer".

**Comment by dhgrs** [comment]
Sorry for the confusion. I wanted to tell you that "the demo page doesn't express implementation correctly". "Reconstructions" is one of the examples.

I think residual blocks are not used in the author's results but it's efficient. And I don't know whether BN and dropout are used or not. But may be efficient too.

Now I don't have machines to try it,  so if you can, please try? You can change the encoder's architecture in `models.py`.

https://github.com/dhgrs/chainer-VQ-VAE/blob/58628304d60f778be0620360c663b7be00bf1181/models.py#L9-L27
